apiVersion: v2
name: poc-app
description: POC App
type: application
version: 0.0.1

dependencies:
  - name: nginx
    alias: nginx1
    version: 12.0.0
    repository: https://charts.bitnami.com/bitnami
  - name: nginx
    alias: nginx2
    version: 12.0.0
    repository: https://charts.bitnami.com/bitnami
