apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: workflow-release-8fb46d4356fe656c-chart-k8s-tw-deploy-prod-2931652957
  generateName: timeouts-step-
spec:
  entrypoint: sleep
  templates:
  - name: sleep
    container:
      image: argoproj/argosay:v2
      command: [bash, -c]
      args: ["echo 123; sleep 1d"]
    activeDeadlineSeconds: 30
