apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: wf2
spec:
  entrypoint: sleep
  templates:
  - name: sleep
    container:
      image: argoproj/argosay:v2
      command: [bash, -c]
      args: ["echo 123; sleep 1s"]
    activeDeadlineSeconds: 10
